### ISSUE TITLE
Add contributing.md file

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/titanic_survival_exploration#1]
Update contribution guidelines.

- [ ]  Add how to fork the repo
- [ ] Creating branches
- [ ] Pushing changes to the master repo. 

We will love to look into your valuable contribution.

With :heart: from Github

**Comment by Yogendra0Sharma** [comment]
@prateekiiest : can I take this issue?

**Comment by prateekiiest** [comment]
Yeah sure @Yogendra0Sharma
