### ISSUE TITLE
Add Issue and Pull Request Template

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/titanic_survival_exploration#5]
Search existing such templates [here](https://github.com/blog/2111-issue-and-pull-request-templates)

**Comment by schalkneethling** [comment]
@TremaineNeethling this looks like something you can pick up

**Comment by schalkneethling** [comment]
@prateekiiest do you have something in mind for the template?

**Comment by prateekiiest** [comment]
Some thing like this

## Issue

- [ ] Issue number
- [ ] Issue name should be proper and not something vague
- [ ] Description about the issue.
- [ ] which files it requires changes 


## PR
- [ ] Issue number it addresses.
- [ ] PR name should be self descriptive.
- [ ] Describe your changes in brief and which files you changed.

**Comment by schalkneethling** [comment]
Myself and @TremaineNeethling talked about this and here are some thoughts:

* Issue number

This is auto generate by Github when a new issue is created so, I reckon we can leave this

*  Issue name should be proper and not something vague

Something like, “Please provide a short, clear description of the problem”

*  Description about the issue.

“Please describe the problem you encountered, and steps to reproduce”

*  which files it requires changes

This is not always known at issue creation time so, we can either reword or, leave this off. If reword, it can perhaps read something like: “If known, which file(s) needs to be changed?”

**Comment by schalkneethling** [comment]
I wonder if the PR requirements should be part off the README/CONTRIBUTING files? I often feel like there could be two sections to a contributing/get involved section. 

1) Assume prior knowledge
2) Assume no prior knowledge

Have 2 be first and allow other users to skip over the basics. Thoughts?

**Comment by prateekiiest** [comment]
I feel that PR requirements be included in the contributing.md  section.

**Comment by ghost** [comment]
@prateekiiest Here is my pull request https://github.com/prateekiiest/titanic_survival_exploration/pull/6
