### ISSUE TITLE
create separate folder for extracting features from data set

### ISSUE THREAD

**Issue by prateekiiest** [prateekiiest/titanic_survival_exploration#9]

**Comment by imVivekGupta** [comment]
Like, extracting different columns from the dataframe as separate attributes?

**Comment by prateekiiest** [comment]
yes @imVivekGupta

**Comment by imVivekGupta** [comment]
Cool! I can do this.

**Comment by vishal1383** [comment]
In this can I add the new compound feature 'Title' in that too?(On how to extract Title like Mr, Ms. etc.)from the Name which is generally not used.We can get the information regarding the Gender and much other info from the dataset in that way too.It will be about extracting Title from name.

**Comment by prateekiiest** [comment]
sure @vishal1383 , that would be great

**Comment by vishal1383** [comment]
Thanks .Working on it

**Comment by imVivekGupta** [comment]
Yes, this would be an important feature.

**Comment by prateekiiest** [comment]
I am closing this. 😄 . Open if any updates
